import './globals.css'
import { Inter } from 'next/font/google'
import { CounterProvider } from './context/counterProvider';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Create Next App',
    template: `%s | Next App`
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  team,
}: {
  children: React.ReactNode,
  team: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header>
      <Link href="/" className="underline mr-4">
        Home
      </Link>
      <Link href="/about" className="underline mr-4">
        About
      </Link>
      <Link href="/users" className="underline">
        Users
      </Link>
      </header>
        <div>{team}</div>
        <CounterProvider>{children}</CounterProvider>
      </body>
    </html>
  )
}
